### ISSUE TITLE
Connect notebook directly to Gsheet

### ISSUE THREAD

**Issue by gpsaggese** [kaizen-ai/kaizenflow#1007]
On-board on cmamp to use our system (e.g., Docker)

Create a notebook to
- Read and save data from Google Sheet directly
   - We have an interface to manipulate Gsheet in place
   - See ./docs/coding/all.gsheet_into_pandas.how_to_guide.md
   - Google has changed the authentication lately so maybe the doc needs to be updated
- Use filter to remove/select some rows
  - Compute stats
- Creates a new tab in the same Gsheet with the “cleaned version”
- Then find emails of people using first, last, and company
   - See APIs here https://docs.google.com/document/d/1O1PJFWMiX4hZH7tzzWEnXSpBKGb-654T7MwVmf26O8M/edit#heading=h.r7dh5iptnhwu
   - We want to use hunter.io (we have an API key)
   - Optional, if we can't find an email, we want to use another provider (e.g., dropcontact.io, or TheDataScraper)

**Comment by Shaunak01** [comment]
@gpsaggese Yet to be onboarded. Any example data sheet to create for this notebook?
