### ISSUE TITLE
Soccer prediction

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#1008]
This is the first step towards Prediction Engine of Everything. We decided to work on Soccer prediction model.

Goal of this EPIC:
- Look for all the datasets available related to soccer.
- Do some EDA on those datasets.
- Build baseline from current research / SOTA work.
- Work on improving baseline. 

FYI @gpsaggese @samarth9008 @tkpratardan

**Comment by tkpratardan** [comment]
@gpsaggese @sonaalKant 

Moving forward, we will keep track of tasks and lab notes for the insights in the following docs:

Tasks:
https://docs.google.com/document/d/1O7osnK_E4I3KN64vyN2aFZt8s4usG9P6C6shFbT84-4/edit?usp=sharing

Lab Notes:
https://docs.google.com/document/d/1WTpRpIGW-4AH-UN7tYerFetc21JhmvhowVkRSYqHE8M/edit?usp=sharing

**Comment by tkpratardan** [comment]
For easier tracking: 

> * Look for all the datasets available related to soccer.
  
Issue : #830
FIle: [Gsheet](https://docs.google.com/spreadsheets/d/10DiFOosnKqR70cI6TrKa9kRH2Z08kN-j/edit?usp=drive_link)

 
> * Do some EDA on those datasets.

Issue : #1010 & #992
PRs: #920 & 994

> * Build baseline from current research / SOTA work.

Issue: #997 
PR: #1006 

> * Work on improving baseline.
Yet to be done

**Comment by gpsaggese** [comment]
We are going in the right direction. Very good.

A few notes:
1) All issues should go in the Epic https://app.zenhub.com/workspaces/cm-615371012ed326001e044788/issues/gh/kaizen-ai/kaizenflow/1008
- I've done that

2) I've merged
https://docs.google.com/document/d/1O7osnK_E4I3KN64vyN2aFZt8s4usG9P6C6shFbT84-4/edit
with my tasks
KaizenAI - Sports betting - Issues specs
https://docs.google.com/document/d/1ugyVCQxyjKQLGWzCKG0I4PDpgVBSr74NvlaDTglgHuo/edit

3) Lab notes
- Very good
- I've reorg to use dates in reverse chronological order
- Let's use this style

Let's keep using these conventions to keep things neat. Good stuff.
