### ISSUE TITLE
Add functions to compute hit rate

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#1020]
Given a df populated with pred and act outcome compute hit rate for the 3 classes (win, lose, draw)
   - Ideally with confidence interval using a simple Bernoulli hypothesis

Let’s compute the confusion matrix and the F1 metric for the methods we have tried.

**Comment by gpsaggese** [comment]
Yes, this is the granularity of tasks.

Let's implement the code using our approach to write beautiful code.

Ok to cut some corners, e.g.,
- no need to unit test (for now)
- no need to make the code super reusable

The goal is to build a quick end-to-end prototype.

We'll add more people to this project to make things better.
