### ISSUE TITLE
Update notebooks

### ISSUE THREAD

**Issue by tkpratardan** [kaizen-ai/kaizenflow#1026]
Update notebook to visualize the goodness of fit in https://github.com/kaizen-ai/kaizenflow/blob/master/research_amp/soccer_prediction/sota_baseline_glm.ipynb

**Comment by gpsaggese** [comment]
1) Epic and estimate pls

2) How do you want to measure the goodness of fit?

3) Let's move all the code from the notebook to a lib so it's easier to review / run.
Notebooks should only contain calls and some light coding.
