### ISSUE TITLE
Clean up notebooks

### ISSUE THREAD

**Issue by tkpratardan** [kaizen-ai/kaizenflow#1036]
- Factor out common code in notebooks in /research_amp/soccer_prediction and add it to utils.py
- Clean up paired_t_test.ipynb, sota_baseline_glm.ipynb

**Comment by samarth9008** [comment]
@sonaalKant Can this be outsourced to the new people?

**Comment by gpsaggese** [comment]
Let's have the clean up done by the author of code. Certainly adding unit test can be outsourced, but the code is not stable enough IMO.
