### ISSUE TITLE
Unit tests limit_price_computer_using_volatility.py and limit_price_computer_using_spread.py

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#1037]
[ oms/limit_price_computer/limit_price_computer_using_spread.py](https://github.com/kaizen-ai/kaizenflow/blob/master/oms/limit_price_computer/limit_price_computer_using_spread.py)

[oms/limit_price_computer/limit_price_computer_using_volatility.py](https://github.com/kaizen-ai/kaizenflow/blob/master/oms/limit_price_computer/limit_price_computer_using_volatility.py)

In these two files, we have function `calculate_limit_price()`

We just want to extend the existing unit tests if an invalid `side` is supplied as the argument.

Take a look at the test file of this class to get a sense on how to proceed with the issue.

You do not need to test the whole functions, but just when the user supplies invalid side

See unit test [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style
Also highly recommend to read this [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#save-reviewer-time) before submitting 1st PR

FYI @gpsaggese @sonaalKant @DanilYachmenev

**Comment by samarth9008** [comment]
@heanhsok Lets start with this simple issue for now

**Comment by dremdem** [comment]
@heanhsok 
Can you please assign an epic.

**Comment by samarth9008** [comment]
@dremdem Kaizen-ai is for interns. they will not have access to zenhub.

**Comment by gpsaggese** [comment]
Yes, let's only ping people on cmamp to assign Epic.
Mentors should be in charge of managing the project management part.

Do we need to update the EpicMeister docs?

**Comment by heanhsok** [comment]
Closing as PR is merged.
