### ISSUE TITLE
Test `oms/child_order_quantity_computer/child_order_quantity_computer.py::get_range_filter`

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#1038]
We want to test [`oms/child_order_quantity_computer/child_order_quantity_computer.py::get_range_filter`](https://github.com/kaizen-ai/kaizenflow/blob/c3ac308a1512e38ae29803dfde7223c367cb6a44/oms/child_order_quantity_computer/child_order_quantity_computer.py#L97)

This function calls an abstract method which is implemented in the child classes. 

https://github.com/kaizen-ai/kaizenflow/blob/c3ac308a1512e38ae29803dfde7223c367cb6a44/oms/child_order_quantity_computer/dynamic_scheduling_child_order_quantity_computer.py#L125

https://github.com/kaizen-ai/kaizenflow/blob/c3ac308a1512e38ae29803dfde7223c367cb6a44/oms/child_order_quantity_computer/static_scheduling_child_order_quantity_computer.py#L101

Implement the test accordingly for both the classes

See unit test [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style
Also highly recommend to read this [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#save-reviewer-time) before submitting 1st PR

FYI @gpsaggese @sonaalKant @DanilYachmenev

**Comment by samarth9008** [comment]
Any updates @gurtajbir?

**Comment by samarth9008** [comment]
@gurtajbir Seems like you have other commitments. Not an issue. Re-routing it to @smitpatel49. Let us know when you are available to commit to the project.


FYI @DanilYachmenev

**Comment by samarth9008** [comment]
There are already tests written for this files

https://github.com/kaizen-ai/kaizenflow/tree/master/oms/limit_price_computer/test

Feel free to continue in them

**Comment by smitpatel49** [comment]
I am a bit confused, shouldn't the test cases be in 

[oms/child_order_quantity_computer/test](url) for child_order_quantity_computer?

**Comment by samarth9008** [comment]
Oh yeah my bad,

As per spec, You need to write tests in two different file. One is already created. Another you need to create.

**Comment by smitpatel49** [comment]
I think I can write the test for both static and dynamic classes in their respective test case classes.

**Comment by samarth9008** [comment]
Sg, I see both the files have common test files. Ok to edit in the same file.

**Comment by smitpatel49** [comment]
Hello @samarth9008, I am still occupied in a commitment, but I will complete this in a day or two.

**Comment by DanilYachmenev** [comment]
done
