### ISSUE TITLE
Make `generate_limit_order_price()` function private

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#1039]
Convert [`generate_limit_order_price()`](https://github.com/kaizen-ai/kaizenflow/blob/c3ac308a1512e38ae29803dfde7223c367cb6a44/core/finance/execution.py#L22) to a private function

Check and update calls to all the places

Easy way to find where this function is used, is by using our internal tool `jackpy`

E.g.:

```shell
> jackpy generate_limit_order_price
```

Remove TODO from the line above the function is defined.

Also highly recommend to read this [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#save-reviewer-time) before submitting 1st PR

FYI @gpsaggese @sonaalKant @DanilYachmenev

**Comment by smitpatel49** [comment]
I am unable to access the files in core/finance/execution.py and core/finance/test/test_execution.py @samarth9008

**Comment by smitpatel49** [comment]
I am unable to access the files in core/finance/execution.py and core/finance/test/test_execution.py @samarth9008.

**Comment by DanilYachmenev** [comment]
@smitpatel49 can you open this link?
https://github.com/kaizen-ai/kaizenflow/blob/master/core/finance/execution.py

if not, what is the output?

**Comment by smitpatel49** [comment]
@DanilYachmenev, I can access it now. I think I have some issue with my Virtual Machine, I have faced something like this before. Thanks for the help though.

**Comment by DanilYachmenev** [comment]
done, closing
