### ISSUE TITLE
Improve Poisson model Predictions

### ISSUE THREAD

**Issue by tkpratardan** [kaizen-ai/kaizenflow#1050]
The Poisson regression model has a couple of issues: 
-  some sort of dependence between the two playing teams is introduced by the fact that the strength parameters of each team are present in the Poisson means of both teams. Experiment with a univariate poisson model, where the goals just depend on the team and a given home advantage.

- Draws probability is being underestimated which is results in no draw predictions for the model. 
 One way to fix this issue was to use the Maximum likelihood on the joint probabilities of the goals predicted, i.e:
     `predicted_outcome = argmax(P(Goals_home = x, Goals_home=y)), where 0<=x,y<=10`
     However this resulted in lesser accuracy (<33%)

The idea is to select an ideal approach that fits with the expectations of integrating to KaizenFlow pipeline:
 i) Use inflated probabilities for the draw scores (Dixon - coles method) : -[reference](https://watermark.silverchair.com/jrsssc_46_2_265.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA1swggNXBgkqhkiG9w0BBwagggNIMIIDRAIBADCCAz0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8S75WfU8Cg0kp2SEAgEQgIIDDmMunkBqMSZ6kcEIRD4iEZBwZHxZfy9iKkKFREc8Emlyt9fO4PAl0dgYTFwVnVOUQeiiZOHaG8ta5bRDgCAKfeRE6E4HM4egKrDhAJzVCyJgNMZT5rIXkMS6KSZ8SxGu4_UCKCl6tQgChLvWijCy4P_zxns796VBC-8ig5da27oAodGXQfaRep8ar2gPnzAFBrCFB6iTn6yy25zB6AEFQ7qDm9YwJwPhBG8YRJ3VFdZh7kXsLNqPvtCZk-Vn2DnaIgm7-ETGWy0uKw1Ih-iF_oHZ3bY77dsH4BFzhish617uWnT1VBKPgUJuc85PC8aLo7gXTNLIW9OgbFLknimef4hlooDpih2XxHQYdyOg_c_RK9EL8i5HgAlYUTric-vJ_nUkCBnAxkjYMR-YG9Vl0ZT2rrUGhBVWzXneJgGeR0b20U_AMCCeCT-QM3MO7m7pVRm0l9IkXbX3mJGE9IK4A2nDcktZM9OnrDnr8YOGTpEmUHy68M5DzB9JcHd5LmyvaR2toWfQUwbTNEkllKaiLvrqnpya2m_9yuJnMqDSO-4kRGIO62UsXOJcO0JXm31ejYGDgRNbb5dJ11RvLeqTCKZqu0MK_hJq8s23AU0ojMVrTW1bJnpj9c-00FhtflYFK2aPt-y890-ZA96gDAP6NzewUci9Z--PymXbjwyTqhebA9DjLzUy3to8giFSKD3GsA6SouDEgk-PP4E9g3772VLG0o3-nPlelX1uRPDdJjaayIv-W8ES1l_8K0oYjjaWaS8Tb0Ob-5Loid0TlItpSk-oPX25PNyOA4mWKy0i0pw5gxI9vfIYagxCgKcQxdZpa9hYhpCLTVrV_Y0_8jY34HXeHP3mDMIAH9j7jcxaNh7ybaSkyHeG5_0_vFi7LlSTIgpokzczcW-Cqkg3rGkN0E4pTreDl4WVW51JVrZZKqAc7IfpJABcu0ub7LqhGWlc21xDjlW3HZvaehx3TT8zf7_h1hCwCA4L-CEZvJgbDx4avSi6jhoTiKcaCDQO7q4XVz2N9sIrY-okLfV0Au4w)  
Simple change preserves the model complexity

ii) Use a complex bivariate model: [-reference](http://www2.stat-athens.aueb.gr/~jbn/papers2/08_Karlis_Ntzoufras_2003_RSSD.pdf)
 Despite the dependence introduced in mean goals estimation, this may not be a sufficiently rich model to cover the interdependence between two teams. Joint probabilities will no longer remain independent.

iii) Introduce time-dynamics in estimating the response variable (goals) : -[reference](https://discovery.ucl.ac.uk/id/eprint/1503449/1/Kristensen_PARX-JEF-Rev1-25-Feb-2016_GC.pdf) 

Document the results obtained [here](https://docs.google.com/document/d/1WTpRpIGW-4AH-UN7tYerFetc21JhmvhowVkRSYqHE8M/edit?usp=drive_link) 

@gpsaggese @sonaalKant

**Comment by sonaalKant** [comment]
This was an experiment branch which is now modified and working code is in a different PR https://github.com/kaizen-ai/kaizenflow/pull/1073
