### ISSUE TITLE
On-board Mihir Gujarathi

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#1071]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old) 
  - [x] **Read [How to organize your work](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md)**
  - [x] **Read [Quick start for developing](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md)**
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works and read about our docker methodology
  - [x] **Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully** 
     - OK if some are failing while running it
  - [x] **Read [Kaizen Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)**
  - [ ] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] **Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)**
  - [x] **How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)**
  - [x]  If you are graduating soon and you would like to get a full-time job in
  one of the companies in the KaizenFlow ecosystem reach out to GP at
  gp@kaizen-tech.io

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant  @gpsaggese

**Comment by mihir1906** [comment]
@samarth9008 @sonaalKant I wanted to inform you that I have successfully set up the Kaizenflow development environment on VMware for Ubuntu and have thoroughly read all the assigned documents. Could you please let me know when I will be assigned the warm-up issue? I am eager to get started. Thank you very much!

**Comment by samarth9008** [comment]
Assigned - https://github.com/kaizen-ai/kaizenflow/issues/1076
