### ISSUE TITLE
Improve chatGPT assistant integration

### ISSUE THREAD

**Issue by why2000** [kaizen-ai/kaizenflow#631]
This is a follow-up of #624
Fixing the conversations and adding docstrings for `helpers/hchatgpt.py`
Also, as mentioned here https://github.com/sorrentum/sorrentum/pull/625#discussion_r1446024333 we may want to have `openai` installed in our image. 
A detailed usage doc is created at `docs/work_tools/all.chatgpt_api.how_to_guide.md`

**Comment by gpsaggese** [comment]
No need to complicate the container flow, let's just leave the try-catch-install since it works fine

**Comment by gpsaggese** [comment]
Next steps:
- Move to cmamp
- Comments from the PR

**Comment by why2000** [comment]
FYI @samarth9008 
This issue is already done, and it is integrated into cmamp in AmpTask1786
