### ISSUE TITLE
Improve all.write_unit_tests.how_to_guide.md

### ISSUE THREAD

**Issue by tkpratardan** [kaizen-ai/kaizenflow#729]
This issue is created to update ./docs/coding/all.write_unit_tests.how_to_guide.md with the following changes:

1. Add the high-level unit test skeleton along with a comment on writing unit tests, as pointed [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1516865798)
2. Add a reference for checking the output of assertions in unit tests, as pointed [here](https://github.com/sorrentum/sorrentum/pull/717#discussion_r1516868901)

cc: @gpsaggese @sonaalKant @samarth9008

**Comment by gpsaggese** [comment]
Good job following the process. 

Besides the spot changes, pls read top to bottom and propose updates based on your experience going through the text.
Then you can do a PR.

**Comment by samarth9008** [comment]
@tkpratardan Can this issue be closed?

**Comment by tkpratardan** [comment]
@samarth9008 
We will have to make changes to the doc with the mentioned suggestions. I can do that this week and close it after it is done. Let me know if this works.

**Comment by samarth9008** [comment]
> Let me know if this works.

sgtm

**Comment by sonaalKant** [comment]
Closing, this is done and merged.
