### ISSUE TITLE
Add unit test binance websocket extractor

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#747]
We aim to enhance our binance WebSocket library by incorporating comprehensive unit tests. The library is responsible for two primary functions: downloading historical trades data and establishing a WebSocket connection with Binance for real-time acquisition of bid/ask, OHLCV, and trades data. This issue focuses specifically on creating unit tests for the WebSocket functionality.

Code Location:
[Extractor.py](https://github.com/sorrentum/sorrentum/blob/master/im_v2/binance/data/extract/extractor.py)

Key Objectives:

- Mock Interaction with Binance: Implement mock interactions to simulate communication with the Binance WebSocket.
- Test Methods:
    - _download_websocket_bid_ask
    - _download_websocket_ohlcv
    - _download_websocket_trades
- Follow DRY Principle: Ensure adherence to the "Don't Repeat Yourself" (DRY) principle throughout the testing process to maintain code efficiency and readability.

FYI @jsmerix

**Comment by Jd8111997** [comment]
@sonaalKant, in which existing file should I add functionality for unit test cases?

**Comment by sonaalKant** [comment]
[im_v2/binance/data/extract/test/test_binance_extractor.py](https://github.com/sorrentum/sorrentum/blob/master/im_v2/binance/data/extract/test/test_binance_extractor.py)

**Comment by sonaalKant** [comment]
We will be continuing this on cmamp as VPN access is required. https://github.com/cryptokaizen/cmamp/issues/8071 . Closing here.
