### ISSUE TITLE
Unit test load_db_data

### ISSUE THREAD

**Issue by jsmerix** [kaizen-ai/kaizenflow#752]
The function is located here

https://github.com/sorrentum/sorrentum/blob/e3082a98b034acac55f62f116a8868a1598185bd/im_v2/common/db/db_utils.py#L366

Specs:

- We want to mock the interaction with the database, the goal is just to capture the correctness of the constructed query
- In this issue let's aim for statement level coverage, AKA each line of the code should be tested in at least one unit test
- Let's pay special attention to the `time_interval_closed` parameter

Let's aim for frequent raising of PRs, 1 work day = 1 PR (it's not important to push fully functioning code), can you also set @sonaalKant as reviewer?

**Comment by Jd8111997** [comment]
@jsmerix, In which file shall I add functionalities for mock interactions?

**Comment by jsmerix** [comment]
https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/db/test/test_db_utils.py

**Comment by Jd8111997** [comment]
@jsmerix I believe he is referring to existing code in the `test_db_utils.py` file that he wrote.
@Er1-x Is it still under progress ?

**Comment by Er1-x** [comment]
> @jsmerix I believe he is referring to existing code in the `test_db_utils.py` file that he wrote. @Er1-x Is it still under progress ?

Yes, It's still on progress

**Comment by samarth9008** [comment]
@Jd8111997 Can this be closed?
