### ISSUE TITLE
On-board Srujana Komaravolu

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#759]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/sorrentum.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [ ] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @sonaalKant  @gpsaggese

**Comment by SrujanaKomaravolu** [comment]
Hi Samarth,

Can you please tell me what work i have to do?

Thanks,
Srujana

**Comment by samarth9008** [comment]
> Can you please tell me what work i have to do?

For now you have to follow checklist commented https://github.com/sorrentum/sorrentum/issues/759#issue-2221386862

Warm-up issue will be simple issue to test that read all the docs in details especially coding style

After you will get work as described in the job description

**Comment by SrujanaKomaravolu** [comment]
Ok, I will do it.

Thanks,
Srujana

**Comment by samarth9008** [comment]
Hows the progress?

**Comment by SrujanaKomaravolu** [comment]
Still working on it.


Thanks,
Srujana

**Comment by SrujanaKomaravolu** [comment]
As indicated in comment 759, my current task involves establishing the
docker environment and examining the docs, especially codingstyle. I would
like to confirm and clarify my responsibilities in this regard.

Thanks,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hello,

I'd like to inform you that I've finished reviewing the 759 documents. At
present, I'm in the process of running Docker on my VM.

Best regards,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hello,

I'd like to inform you that I've finished reviewing the 759 documents. At
present, I'm in the process of running Docker on my VM.

Best regards,
Srujana

**Comment by samarth9008** [comment]
Please tick each item that you have completed.

**Comment by samarth9008** [comment]
Whats the update on it?

Pls use github GUI for reply. Replying through email makes it have unwanted information

**Comment by SrujanaKomaravolu** [comment]
i am currently working on task 3 , on docker

**Comment by samarth9008** [comment]
Pls use github GUI for reply. Replying through email makes it have unwanted information

**Comment by SrujanaKomaravolu** [comment]
Hello,

Apologies for the delay in my work. Starting from this week, I will be
dedicating myself fully to the project.

Thank you,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hello,

Apologies for the delay in my work. Starting from this week, I will be dedicating myself fully to the project.

Thank you,
Srujana

**Comment by samarth9008** [comment]
Are you done with these two as well?

Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
 How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)

**Comment by SrujanaKomaravolu** [comment]
I am on it

**Comment by SrujanaKomaravolu** [comment]
Hi ,

I have completed the tasks.

Thanks,
Srujana

**Comment by komaravolusrujana** [comment]
I'll go through the tasks again .
Sorry for the inconvenience. 

Thanks,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hi Samarth,

I've submitted a request for access to Google Drive. Could you please check on this for me?

Thanks,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hi Samarth,

I've submitted a request for access to Google Drive as well as requested for permission to join the group  Could you please check on this for me?

Thanks,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hello Team,

I've been granted permission to join the group, and I've successfully completed all the assigned tasks except for the warm-up issue. Could you please provide guidance on how to address this?

Thank you,
Srujana

**Comment by samarth9008** [comment]
Assigned https://github.com/kaizen-ai/kaizenflow/issues/785

**Comment by SrujanaKomaravolu** [comment]
Hi,
I am writing to inform you that I have successfully completed my exams and am now fully available to contribute to our project. I am eager to dedicate my time and skills to the project's success and am prepared to commit myself wholeheartedly to our collective efforts.

Thank you for your understanding and support.

Best regards,
Srujana

**Comment by Srudemo** [comment]
Hi,
I am writing to inform you that I have successfully completed my exams and am now fully available to contribute to our project. I am eager to dedicate my time and skills to the project's success and am prepared to commit myself wholeheartedly to our collective efforts.

I am requesting the team to allocate me task, which I couldn't complete  unfortunately because of my finals.

Thank you for your understanding and support.

Best regards,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hi,
I am writing to inform you that I have successfully completed my exams and am now fully available to contribute to our project. I am eager to dedicate my time and skills to the project's success and am prepared to commit myself wholeheartedly to our collective efforts.

I am requesting the team to allocate me task, which I couldn't complete unfortunately because of my finals.

Thank you for your understanding and support.

Best regards,
Srujana

**Comment by SrujanaKomaravolu** [comment]
Hi,
I am writing to inform you that I have successfully completed my exams and am now fully available to contribute to our project. I am eager to dedicate my time and skills to the project's success and am prepared to commit myself wholeheartedly to our collective efforts.

I am requesting the team to allocate me task, which I couldn't complete unfortunately because of my finals.

Thank you for your understanding and support.

Best regards,
Srujana
