### ISSUE TITLE
Start downloading data 

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#762]
We would like to have a pipeline to fetch data from these sources on which later we will evaluate our model. 

[goperigon.com](https://goperigon.com/)
[newsdata.io](https://newsdata.io/)
[mediastack.com](https://mediastack.com/)
[thenewsapi.com](https://thenewsapi.com/)
[marketaux.com](https://marketaux.com/)

Lets try to write the code which follows OOP principles and well documented. Let's start with using free version of each api. If needed we will upgrade.

FYI @gpsaggese

**Comment by tkpratardan** [comment]
@sonaalKant 
What would be the path for the script?

**Comment by gpsaggese** [comment]
What's the plan exactly? Which data sources? What is the format? What does the data look like?

Let's put together a notebook showing a bit of data so we can make an informed decision, and use the Gdoc to track the results

**Comment by tkpratardan** [comment]
@gpsaggese 

> What's the plan exactly? Which data sources? What is the format? What does the data look like?

As mentioned, the plan here is to create a data pipeline to fetch data from the specified datasources. We would initially be using their free API keys (limited requests). The code would account for the following:
- Separate classes for data pipelines of each data source. These classes would take in all inputs needed for fetching the data, viz:
   1.   `endpoints`: If they exist, we will have an argument where we can specify the interested endpoint of API.
   2.  query parameters like `keywords (q), categories, topics, start date, end date` 

We get a JSON response typically consisting the article information like headline, article source, URL, article text, summary, etc. Some of the data sources provide a sentiment analysis. All articles from the API request query are then stored in a dictionary, which will be the return of the `fetch_data()` method for each class. 


> Let's put together a notebook showing a bit of data so we can make an informed decision, and use the Gdoc to track the results

I will raise a draft PR once the filepath is confirmed and update the GDoc accordingly.

Let me know if this makes sense.

**Comment by sonaalKant** [comment]
Initial steps on PEOE, closing as experiment is completed and merged.
