### ISSUE TITLE
Extend `is_pickleable()` unit testing

### ISSUE THREAD

**Issue by DanilYachmenev** [kaizen-ai/kaizenflow#766]
In `helpers/hintrospection.py` we have `is_pickleable()` that checks if input is eligible for pickling

We need unit to unit test this function:
- Unit test both `mode` options
- Unit test following input types:
  - [x] Not callable (`int` or `str`)
    - Should return `True` for both modes
  - [x] Bound to object method
    - see `is_bound_to_object()` check for reference
      - Should return `False` for both modes
  - [x] Lambda function (e.g. `lambda x: x`)
    - Should return `False` for both modes
  - [x] A class object with pickleable param values
    - See `_Abstract_ClassA` in `helpers/test/test_hobject.py`
    - Should return `True` for both modes
  - [x] A class object with non-pickleable param values
    - See `_ClassB` in `helpers/test/test_hobject.py` for reference
    - Should return `True` for `"type_search"` mode and `False` for `"try_and_catch"` mode

The last 2 cases are particularly interesting, because we do have classes with non-pickleable param values in our configs and we should be able to detect it with `"try_and_catch"` mode and demonstrate that `"type_search"` mode fails to do so

For this you can create test classes for such cases like in `helpers/test/test_hobject.py`, e.g.:

```
class _ClassPickleable:
    """
    Class with pickleable param values.
    """

    def __init__(self) -> None:
        self._arg1 = 1
        self._arg2 = ["2", 3]

class _ClassNonPickleable():
    """
    Class with non-pickleable param values.
    """

    def __init__(self) -> None:
        self._arg1 = lambda x: x
        self._arg2 = 2
```

Please, read [unit test doc](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) and files with similar tests in order to comply with our code standarts

Assigning @samarth9008 to re-distribute.
Do in multiple PRs please, each checkbox 1 by 1 in order to iterate faster

FYI @PomazkinG

**Comment by PomazkinG** [comment]
guys, this is how it should be done, bravo!

**Comment by ttiaNlluu** [comment]
Can you explain more about the mode options? Thanks.

**Comment by DanilYachmenev** [comment]
> Can you explain more about the mode options? Thanks.
`is_pickleable()` has param named `mode` and it has only 2 acceptable values: `"type_search"` and `"try_and_catch"`, see the function docstrings for detailed explanation and check the code to understand how they work exactly

So we need to unit test func behaviours for both `mode` values

See already existing `Test_is_pickleable1` - you need to refactor it because now it tests only default behaviour

**Comment by ttiaNlluu** [comment]
Let me know where I'm wrong: `is_pickleable()` in `helpers/hintrospection.py` only has one param `object`, I didn't find other param named `mode`.

**Comment by samarth9008** [comment]
@DanilYachmenev The code in the `is_pickleable()` do not have param named `mode`. Can clarify on this?

https://github.com/sorrentum/sorrentum/blob/b2038a09192848d50da5b015dd1ecb6705883d18/helpers/hintrospection.py#L161

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev The code in the `is_pickleable()` do not have param named `mode`. Can clarify on this?
> 
> https://github.com/sorrentum/sorrentum/blob/b2038a09192848d50da5b015dd1ecb6705883d18/helpers/hintrospection.py#L161

Indeed, it is not exposed there yet because https://github.com/cryptokaizen/cmamp/issues/7683 is not merged and integrated to `sorrentum` yet, will advance on it today

in the meanwhile, good call on testing the existing behaviour on test classes, I will review the code today

**Comment by ttiaNlluu** [comment]
Delete PR #769 and create PR #831.
