### ISSUE TITLE
Unit test `sign_normalize()`

### ISSUE THREAD

**Issue by DanilYachmenev** [kaizen-ai/kaizenflow#784]
There is a `sign_normalize()` in `core/signal_processing/misc_transformations.py` ([link](https://github.com/sorrentum/sorrentum/blob/b2038a09192848d50da5b015dd1ecb6705883d18/core/signal_processing/misc_transformations.py#L197)) that is being used in `cross_feature_pair()`

We need to add unit tests using synthetic test data. Create simple short input signal that is Series or Dataframe. Run the function on it and compare the outcome with string signature (for ref see tests in `amp/helpers/test/test_hpandas.py` e.g. `Test_merge_dfs1`)

Cover the following cases:
- [x] Test Series and DataFrame inputs
- [x] Test different values for `atol`

See [unit test doc](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style

Assigning @samarth9008 to re-distribute

FYI @gpsaggese

**Comment by samarth9008** [comment]
@DanilYachmenev Thanks! Much needed all this issue.

**Comment by ttiaNlluu** [comment]
Delete PR #806 and create PR #814.
