### ISSUE TITLE
Unit test `split_positive_and_negative_parts()`

### ISSUE THREAD

**Issue by DanilYachmenev** [kaizen-ai/kaizenflow#786]
There is a `split_positive_and_negative_parts()` in `core/signal_processing/misc_transformations.py` ([link](https://github.com/sorrentum/sorrentum/blob/b2038a09192848d50da5b015dd1ecb6705883d18/core/signal_processing/misc_transformations.py#L249)) that is being used in `aggregate_single_name_models()`

We need to add unit tests using synthetic test data. Create simple short input signal and run the function on it, compare the outcome with string signature (for ref see tests in `amp/helpers/test/test_hpandas.py` e.g. `Test_merge_dfs1`)

Cover the following cases:
- [ ] Test Series input
- [ ] Test DF input

See [unit test doc](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style

Assigning @samarth9008 to re-distribute

FYI @gpsaggese

**Comment by neha2801-create** [comment]
Apologies for missing. Can you please review now @DanilYachmenev.
