### ISSUE TITLE
Replace sorrentum reference to kaizenflow in the docs

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#813]
We changed the organization name from `sorrenutum/sorreuntum` to `kaizen-ai/kaizenflow`. We want to replace it from the codebase and docs as well

@Sameep2808 

Lets start with replacing all the reference in the docs mentioned in the on-boarding issue

https://github.com/kaizentech-io/kaizenflow/issues/760

For e.g. the old url was https://github.com/sorrentum/sorrentum.git

The new is https://github.com/kaizen-ai/kaizenflow.git

FYI @gpsaggese

**Comment by samarth9008** [comment]
@Sameep2808 

Can you make a TODO list of the all doc dirs and tick them if you have made changes to? Easy to keep track of them

**Comment by Sameep2808** [comment]
List of doc dirs:

- [ ] build
- [ ] coding
- [ ] dataflow
- [ ] datapull
- [ ] deploying
- [ ] dev_tools
- [ ] documentation_meta
- [ ] general_background
- [ ] infra
- [ ] kaizenflow
- [ ] monitoring
- [ ] onboarding
- [ ] trade_execution
- [ ] work_organization
- [ ] work_tools

**Comment by samarth9008** [comment]
@Sameep2808 Lets get done with all these remaining dirs as well

**Comment by samarth9008** [comment]
Closing as merged
