### ISSUE TITLE
PEOE First step: Fetching datasources

### ISSUE THREAD

**Issue by tkpratardan** [kaizen-ai/kaizenflow#830]
So far, we have collected data sources for different games(football, NFL, MLB, cricket, basketball) with information on several attributes that can potentially influence predictions on betting, player performance/progression, etc.  The list of datasets and their source links have been collated in the doc [here.](https://docs.google.com/document/d/1XjQohkZn01dZDtm02gM-btiSn5qnwB9VDaelx7sDxb8/edit)

@gpsaggese @sonaalKant @samarth9008

**Comment by gpsaggese** [comment]
Interesting stuff.

Let's do another round of analysis trying to quantify for each data set:
- number of columns
- number of rows
- years covered
- is there some project already working on this, that we can take inspiration from?

- quality of the data: 1 (poor) - 5 (great)
  - The ideal data set has a lot of columns, lots of rows, and examples of people of already doing some work on it (so it's not a crappy data set)

I would switch to a gsheet for this analysis, so everything is in tabular form.

After this, we can meet and decide which datasets to start downloading and analyzing.

**Comment by tkpratardan** [comment]
@gpsaggese @sonaalKant @samarth9008 
I have made a google sheet with the all the information that I believe would help us making a decision. Please take a look at the [doc](https://docs.google.com/spreadsheets/d/10DiFOosnKqR70cI6TrKa9kRH2Z08kN-j/edit#gid=957947873) and review.

**Comment by gpsaggese** [comment]
Well done.

The next step is to collectively decide which data sets are best to start using for the case study.
Also for the most interesting data sets are there example of analysis done on Kaggle so we can see what's the baseline?

**Comment by tkpratardan** [comment]
> Also for the most interesting data sets are there example of analysis done on Kaggle so we can see what's the baseline?

Yes, I will attach some links in gsheet.

**Comment by sonaalKant** [comment]
I think we can close this.
