### ISSUE TITLE
On-board Smit Patel

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#841]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old) 
  - [x] **Read [How to organize your work](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md)**
  - [x] **Read [Quick start for developing](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md)**
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works and read about our docker methodology
  - [x] **Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully** 
     - OK if some are failing while running it
  - [x] **Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)**
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] **Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)**
  - [x] **How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)**
  - [x]  If you are graduating soon and you would like to get a full-time job in
  one of the companies in the KaizenFlow ecosystem reach out to GP at
  gp@kaizen-tech.io

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant  @gpsaggese

**Comment by smitpatel49** [comment]
Hello @samarth9008, I have completed the required tasks and have my developer environment ready, can you please assign me the warm-up issue.
Thanks.

**Comment by gpsaggese** [comment]
Pls make sure to read also 

<img width="480" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/33238329/07d78120-e018-4335-b8e5-f29668102cbd">

and read the doc several times so that you can internalize it and be more productive. Good luck @smitpatel49 !

**Comment by sonaalKant** [comment]
Once you are done with your reading, then you can start with your warm-up issue. https://github.com/kaizen-ai/kaizenflow/issues/918.

**Comment by smitpatel49** [comment]
Will make sure to go through the documentation thoroughly and will also get started with the warm-up issue. Thank you @gpsaggese,  @sonaalKant.

**Comment by sonaalKant** [comment]
any updates?? @smitpatel49

**Comment by gpsaggese** [comment]
Now that finals are wrapped up, we will be less patient with delays and no progress.
We asked people to pledge a serious effort.
We put energy in training, mentoring, and teaching students, which could be put towards someone/something else.

**Comment by smitpatel49** [comment]
> any updates?? @smitpatel49
Hello @sonaalKant , I completed the task last weekend, I forgot to push the PR as I was overwhelmed with other work. I will however push the PR and update you before afternoon.

**Comment by smitpatel49** [comment]
I am working with my professor on a different project and was occupied in wrapping it up for the last two weeks. I understand that it is no excuse and I apologize for the inconvenience. I will be more efficient with my work. Thank you.

**Comment by samarth9008** [comment]
Closing as done
