### ISSUE TITLE
Add do not respond to email to doc

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#844]
1) @samarth9008 should we add the "do not respond to email" to the doc?

_Originally posted by @gpsaggese in https://github.com/kaizen-ai/kaizenflow/issues/759#issuecomment-2072383994_

**Comment by samarth9008** [comment]
We can add a point to this doc

https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md#writing-and-contributing-code

And also on the on-boarding issue while creating it so needs to update point 6 here

https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/admin.onboarding_process.md#on-boarding-process

**Comment by samarth9008** [comment]
FYI @gpsaggese

**Comment by samarth9008** [comment]
@heanhsok Can you improve this in your current PR as well?

**Comment by heanhsok** [comment]
hi @samarth9008 I have added another bullet point to this doc in the PR

> We can add a point to this doc
> 
> https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md#writing-and-contributing-code

I'm not sure on a good place to add it to this doc as point 6 alreadys include a reference to the doc above. Do you want me to reemphasize it by adding it as another item in the checklist?

> And also on the on-boarding issue while creating it so needs to update point 6 here
> 
> https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/admin.onboarding_process.md#on-boarding-process

**Comment by heanhsok** [comment]
Closed as PRs has been merged.
