### ISSUE TITLE
Refactor the all.submit_code_for_review.how_to_guide.md file 

### ISSUE THREAD

**Issue by neha2801-create** [kaizen-ai/kaizenflow#862]
- In file all.submit_code_for_review.how_to_guide.md:

   - Under Section : Read Python Style Guide
   - Link name : Python Style Guide 
   - Link address : https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/Coding_Style_Guide.md
   - This Link address is broken.

- Replace the Link Address
- Actual Link Address : https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.coding_style.how_to_guide.md

**Comment by neha2801-create** [comment]
- Also found other 2 Link addresses broken:

   - Under Section : Run Linter
      - Link name :  KaizenFlow_development_setup.md
      - Broken Link 1: 
      https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/KaizenFlow_development_setup.md.md

      - Replaced Link :  
      https://github.com/kaizen-ai/kaizenflow/blob/SorrTask862_refactor_the_allsubmit_code_for_reviewhow_to_guidemd_file/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md


    - Under Section : Save Reviewer time ---> Ask for reviews
       - Link name : desc
       - Broken Link 2: 
https://github.com/cryptokaizen/cmamp/blob/master/docs/work_organization/all.use_github_and_zenhub.how_to_guide.md#pr-labels

       - Replaced Link : 
       https://github.com/kaizen-ai/kaizenflow/blob/SorrTask862_refactor_the_allsubmit_code_for_reviewhow_to_guidemd_file/docs/work_organization/all.use_github_and_zenhub.how_to_guide.md#pr-labels

**Comment by samarth9008** [comment]
usually just FYI

Assignee should be someone who is working on the issue


If you want to keep another person informed just tag that person in the issue description. e.g. `FYI @samarth9008 ` something like this should go to issue description instead of assigning them in the issue
