### ISSUE TITLE
Unit test `compute_epoch()`

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#891]
There is a `compute_epoch()` in `core/finance/prediction_processing.py` ([link](https://github.com/sorrentum/sorrentum/blob/b2038a09192848d50da5b015dd1ecb6705883d18/core/finance/prediction_processing.py#L41)) that is being used in `compute_twap_vwap()` 

We need to add unit tests using synthetic test data. Create simple short input Series/Dataframe with pd.Timestamp index. Run the function on it and compare the outcome with string signature (for ref see tests in `amp/helpers/test/test_hpandas.py` e.g. `Test_merge_dfs1`)

Add 4 unit tests:
- [x] 3 for each available `unit` value for a Series input
- [x] 1 for any unit type but on a DataFrame input

See [unit test doc](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style

Assigning @samarth9008 to re-distribute

FYI @gpsaggese @DanilYachmenev

**Comment by aish-nidhi** [comment]
Added 3 unit tests for each available unit value for a Series input.
Tested the code. All 3 test cases passing.
<img width="1432" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/26075339/db4046b3-8f1f-46bd-b8fc-99ad4577bb1d">

Ran linter on the file.

**Comment by DanilYachmenev** [comment]
@aish-nidhi where is PR?

**Comment by aish-nidhi** [comment]
Just created one -[PR SorrTask891]( https://github.com/kaizen-ai/kaizenflow/pull/901)
