### ISSUE TITLE
encountering error while building the the thin environment. 

### ISSUE THREAD

**Issue by Nitesh703** [kaizen-ai/kaizenflow#896]
I'm building the thin environment, when I run the command 
<img width="822" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/b84950a6-0ddc-40d4-ae15-48989b36d96a">

I get the error mentioned in the screenshot. But, at the same time 'venv' folder is also getting created in my src folder, which indicates that environment is setup. So, should I ignore the error message in screenshot?

also, when I try to activate the environment using command "source dev_scripts/setenv_amp.sh". The output is not exactly the same as output mentioned in the document. But, it says SUCCESS at the end.

<img width="779" alt="image" src="https://github.com/kaizen-ai/kaizenflow/assets/57875542/31c87c4b-d049-433c-ad08-2739d30f5abe">

**Comment by samarth9008** [comment]
No need to create new issue for errors you face. Just post it in on-boarding issue.
