### ISSUE TITLE
Unit test `convert_seconds_to_pandas_minutes()`

### ISSUE THREAD

**Issue by DanilYachmenev** [kaizen-ai/kaizenflow#903]
There is a `convert_seconds_to_pandas_minutes()` in `helpers/hdatetime.py`

Add 2 unit tests to `helpers/test/test_hdatetime.py`:
- [ ] input = `300`
- [ ] input = `10`

See [unit test doc](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style and other unit test files for references 

Assigning @samarth9008 to re-distribute

FYI @gpsaggese @DanilYachmenev

**Comment by neha2801-create** [comment]
@DanilYachmenev 

 In helpers/hdatetime.py : 
Function name  is given as    convert_seconds_to_minutes(num_secs: int) -> int: 
But in above description its :  convert_seconds_to**_pandas**_minutes() 

Is there some different function expected  or you referred this function only?
Thanks!

**Comment by DanilYachmenev** [comment]
> In helpers/hdatetime.py : Function name is given as convert_seconds_to_minutes(num_secs: int) -> int: But in above description its : convert_seconds_to_pandas_minutes()

I usually mentions function names and methods with `()` at the end so people can distinguish them for param and class names
specifying input of every function like this would've been to much, so consider such mentions as a reference to Callables

**Comment by DanilYachmenev** [comment]
@samarth9008 who is responsible for implementing integration of touch PRs with cmamp?
Should I do it for whom I review?

**Comment by samarth9008** [comment]
No need to do it. We do regular integration every alternate week and we are going to do it this Friday.
