### ISSUE TITLE
Add unit test for split_universe

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#918]
We would like to add some unit test for `_split_universe` method. https://github.com/kaizen-ai/kaizenflow/blob/a7952ef84cc2ebe93042ccc481486e6ef66ca292/im_v2/common/data/extract/extract_utils.py#L1087

Write 2-3 unit test to check all the corner cases of the method. You will write your tests [here](https://github.com/kaizen-ai/kaizenflow/blob/a7952ef84cc2ebe93042ccc481486e6ef66ca292/im_v2/common/data/extract/test/test_extract_utils.py) 

FYI @samarth9008

**Comment by smitpatel49** [comment]
Hello @sonaalKant , I think this issue needs to be closed as well. Thank you.
