### ISSUE TITLE
Unit test compute_bar_start_timestamps()

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#979]
There is a `compute_bar_start_timestamps()` in core/finance/prediction_processing.py ([link](https://github.com/kaizen-ai/kaizenflow/blob/08ff1fa970e54df630bf14eed3f11f8b5d645d47/core/finance/prediction_processing.py#L18)) that is being used in the lib

We need to add unit tests using synthetic test data:
- Create simple short input signal that is Series/DataFrame
- Run the function on it and compare the outcome with string signature (for ref see tests in `amp/helpers/test/test_hpandas.py` e.g. `Test_merge_dfs1`)

We need 3 test methods:
- [x] Input if a DataFrame with a valid timestamp index with freq
- [x] Input if a Series with a valid timestamp index with freq
- [x] Input if a DataFrame with a not valid timestamp index, no freq (assert the error message)

See unit test [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) to follow the code style
Also highly recommend to read this [doc](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#save-reviewer-time) before submitting 1st PR

FYI @gpsaggese @sonaalKant @DanilYachmenev

**Comment by samarth9008** [comment]
@Nitesh703 

Whats the status?

**Comment by Nitesh703** [comment]
Hello @samarth9008 
I'm done with unit tests. Creating PR now.

**Comment by samarth9008** [comment]
Closing as merged
