### ISSUE TITLE
On-board Surbhi Sharma

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#985]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old) 
  - [x] **Read [How to organize your work](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md)**
  - [x] **Read [Quick start for developing](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md)**
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works and read about our docker methodology
  - [x] **Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully** 
     - OK if some are failing while running it
  - [x] **Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)**
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] **Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)**
  - [x] **How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)**
  - [x]  If you are graduating soon and you would like to get a full-time job in
  one of the companies in the KaizenFlow ecosystem reach out to GP at
  gp@kaizen-tech.io

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant  @gpsaggese

**Comment by surbhi498** [comment]
Hello @samarth9008 & @sonaalKant ,
I'm building the thin environment, when I run the command "source dev_scripts/client_setup/build.sh" to setup,
![WhatsApp Image 2024-05-16 at 3 40 42 PM](https://github.com/kaizen-ai/kaizenflow/assets/62746024/5d5402aa-1c18-4c31-90d3-cc7af26772da)
Although, I commented the line number 11 in requirements.txt still I am getting this error mentioned in the screenshot. But, at the same time, venv is also getting created in my src folder, which indicates that the environment is setup.

**Comment by samarth9008** [comment]
Uncomment this line https://github.com/kaizen-ai/kaizenflow/blob/4ae261d517e9b17dbb92469d165e23cb7fd1d62c/dev_scripts/client_setup/requirements.txt#L12 and then try running it again. 

Copy paste your logs using code format in the comment instead of pictures.

**Comment by surbhi498** [comment]
Thanks, @samarth9008 
can you please confirm do we have to uncomment down package too line number 11 in requirements.txt  while creating the environmental setup?

**Comment by gpsaggese** [comment]
I've fixed a bug in docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md since `source` is not needed.

Does anybody have an idea of the root cause of this glitching issue?
It seems to be Mac vs Linux issue.

If we don't have an elegant solution, let's update the doc with this good tip from @samarth9008

**Comment by surbhi498** [comment]
Hi, @samarth9008 can you add me to a contributor list I have done an environmental setup and my docker container is running and Jupyter Notebook is also launching.

**Comment by samarth9008** [comment]
Can you send the request to join the group as mentioned in the doc?

https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email

**Comment by surbhi498** [comment]
@samarth9008 thanks I have sent the request to join the group.

**Comment by surbhi498** [comment]
@samarth9008 Hi, I have run test cases although some test cases are failing. Can a warm-up issue assigned to me?

**Comment by samarth9008** [comment]
Closing as done
