### ISSUE TITLE
Initial steps on soccer dataset

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#992]
Lets follow the steps to have experiments in organized manner, We will move the data to S3 so that every one can play with the notebook :
- Before proceeding with further EDA, lets divide the data in train/val/test
    - Use a fixed random seed( eg: 12345) so that split is reproducible every time. 
    - If you think the dataset size is small and we don't have enough test samples then do k-fold cross validation
- Do further data analysis / feature engineering on **train set.**
  - you can also start with feature importance ( how features are correlated with label)
 
- Document
   - Try to  maintain your findings / experiments done on the data ( failed or successful everything should be logged)  organized under the header date ( which will be the date you performed those experiments ).

FYI @samarth9008 @gpsaggese @Shaunak01

**Comment by sonaalKant** [comment]
This is complete, @tkpratardan can you post the link of the PR where your work so that we can close.

**Comment by tkpratardan** [comment]
It is PR #994.
