### ISSUE TITLE
Move football data to S3 

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#998]
@tkpratardan Now you have access to S3, lets move the data there and make sure we can run the notebook after loading data from s3. You can organize your data here `s3://cryptokaizen-data-test/kaizen-ai/`

FYI @gpsaggese

**Comment by gpsaggese** [comment]
Let's add a subdir `.../kaizen_ai/soccer_prediction`

Let's use `_` for file names (I think bucket names need `-`)

**Comment by gpsaggese** [comment]
Also Epic and estimate, pls

**Comment by tkpratardan** [comment]
This is done, in terms of moving data. I will change the file naming. Will the bucket remain the same (cyptokaizen-data-test)?

**Comment by sonaalKant** [comment]
bucket can be the same. Feel free to close the issue once you are done.

**Comment by tkpratardan** [comment]
Closing the issue as this is done.
